Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using Unipluss.Sign.Common.Validation;

namespace Lab3.Models
{
    public class Customer
    {
        public string CustomerID { get; set; }
        public string? CustomerName { get; set; }
        [Required]
        [EmailAddress]
        public string? CustomerEmail { get; set; }
        public string? Phone { get; set; }
    }
}

Models/CustomerDB.cs
namespace Lab3.Models
{
    public class CustomerDB
    {
        private static List<Customer> _customers = new List<Customer>()
        {
            new Customer(){CustomerID = "C101", CustomerName = "Jaimaica", CustomerEmail = "jaimaica@gmail.com", Phone = "6477789987"},
            new Customer(){CustomerID = "C102", CustomerName = "Sarath", CustomerEmail = "sarath@gmail.com", Phone = "4169087756"},
            new Customer(){CustomerID = "C103", CustomerName = "Nahom", CustomerEmail = "nahom@gmail.com", Phone = "6479983456"},
            new Customer(){CustomerID = "C104", CustomerName = "Efe", CustomerEmail = "efe@gmail.com", Phone = "4169805632"},
            new Customer(){CustomerID = "C105", CustomerName = "Altamash", CustomerEmail = "altamash@gmail.com", Phone = "6471127856"},
            new Customer(){CustomerID = "C106", CustomerName = "Harsha", CustomerEmail = "harsha@gmail.com", Phone = "4163456987"}

        };

        public static List<Customer> GetCustomer()
        {
            return _customers;
        }
    }
}

Models/ErrorViewModel.cs
namespace Lab3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Lab3.Models
{
    public class Product
    {
        [Required]
        public string ProductCode { get; set; }
        [Required]
        public string? ProductName { get; set; }
        [Required]
        public decimal? Price { get; set; }    
    }
}

Models/ProductDB.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq.Expressions;

namespace Lab3.Models
{
    public class ProductDB
    {
        private static List<Product> _products = new List<Product>()
        {
            new Product(){ProductCode = "P101", ProductName = "Shampoo", Price = 12},
            new Product(){ProductCode = "P102", ProductName = "Conditioner", Price = 14},
            new Product(){ProductCode = "P103", ProductName = "Body Wash", Price = 18},
            new Product(){ProductCode = "P104", ProductName = "Body Lotion", Price = 25},
            new Product(){ProductCode = "P105", ProductName = "Powder", Price = 10},
            new Product(){ProductCode = "P106", ProductName = "Perfume", Price = 6}
        };

        public static List<Product> GetProducts()
        {
            return _products;
        }

      

    }
}

Controllers/CustomerController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab3.Controllers
{
    public class CustomerController : Controller
    {
        [Route("/Customers")]
        public IActionResult List()
        {
            List<Customer> customer = CustomerDB.GetCustomer();
            return View(customer);
        }

        [Route("/Customer/Details/{customerID}")]
        public IActionResult Details(string customerID)
        {
            Customer customer = CustomerDB.GetCustomer().FirstOrDefault(c => c.CustomerID == customerID);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                CustomerDB.GetCustomer().Add(customer);
                return RedirectToAction("List");
            }

            return View(customer);
        }

        [HttpGet]
        [Route("/Customer/Delete/{customerID}")]
        public IActionResult Delete(string customerID)
        {
            Customer selectedCustomer = CustomerDB.GetCustomer().FirstOrDefault(c => c.CustomerID == customerID);
            if (selectedCustomer != null)
            {
                CustomerDB.GetCustomer().Remove(selectedCustomer);
            }

            return RedirectToAction("List");
        }

    }
}

Controllers/HomeController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("/About")]
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;



namespace Lab3.Controllers
{
    public class ProductController : Controller
    {

        [Route("/Products")]
        public IActionResult List()
        {
            List<Product> products = ProductDB.GetProducts();
            return View(products);
        }

        [Route("/Product/Details/{productCode}")]
        public IActionResult Details(string productCode)
        {
            Product product = ProductDB.GetProducts().FirstOrDefault(p => p.ProductCode == productCode);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                ProductDB.GetProducts().Add(product);
                return RedirectToAction("List");
            }

            return View(product);
        }

        [HttpGet]
        [Route("/Product/Delete/{productCode}")]
        public IActionResult Delete(string productCode)
        {
            Product selectedProduct = ProductDB.GetProducts().FirstOrDefault(p => p.ProductCode == productCode);
            if (selectedProduct != null)
            {
                ProductDB.GetProducts().Remove(selectedProduct);
            }

            return RedirectToAction("List");
        }
    }
}

Views/Customer/Create.cshtml
@model Lab3.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Customer</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerID" class="control-label"></label>
                <input asp-for="CustomerID" class="form-control" />
                <span asp-validation-for="CustomerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerEmail" class="control-label"></label>
                <input asp-for="CustomerEmail" class="form-control" />
                <span asp-validation-for="CustomerEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div><br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customer/Details.cshtml
@model Lab3.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Customer Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    <a asp-action="List">Back to List</a> | <a asp-controller="Customer" asp-action="Delete" asp-route-customerID="@Model.CustomerID">Delete</a>
</div>

Views/Customer/List.cshtml
@model IEnumerable<Lab3.Models.Customer>

@{
    ViewData["Title"] = "Customer List";
}

<h1>Customer List</h1>
<a asp-action="Create">Add New Customer</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustomerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phone)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
              <td>

                    @Html.ActionLink("Details", "Details", new {  id = item.CustomerID }) 
                @*<a asp-action="Index">Back to List</a>*@
                    </td>
        </tr>
}
    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail about your site.</p>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Assignment #1 created and developed with ASP.Net Core.</p>
    <p>Developed by: Jaimaica Daisy Eugenio</p>
</div>

Views/Product/Create.cshtml
@model Lab3.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Add New Product</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductCode" class="control-label"></label>
                <input asp-for="ProductCode" class="form-control" />
                <span asp-validation-for="ProductCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Product/Details.cshtml
@model Lab3.Models.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Product Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductCode)
            
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductCode)
            
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
            
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    @*@Html.ActionLink("Edit", "Edit", new { id = model.ProductCode }) *@
    <a asp-action="List">Back to List</a> <a asp-controller="Product" asp-action="Delete" asp-route-productCode="@Model.ProductCode">Delete</a>
</div>


Views/Product/List.cshtml
@model IEnumerable<Lab3.Models.Product>

@{
    ViewData["Title"] = "Product List";
}

<h1>Product List</h1>
<a asp-action="Create">Add New Product</a>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>*@
                <td>
                    @{
                        string strPrice = string.Format("{0:C2}", item.Price);
                    }
                    @strPrice
                </td>
                <td>

                    @Html.ActionLink("Details", "Details", new {  id = item.ProductCode }) 
                @*<a asp-action="Index">Back to List</a>*@
                    </td>
    
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="List">Customers</a>
                        </li>
                         <li class="nav-item">
                           <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Assignment1 - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>